### PR TITLE
IOS #35 Fix contact collection view scroll lag

### LINKED ISSUE #35: Fix lag while scrolling through pages of contact cards
The database is hit too often on scrolling through contact cards. Async is the probable method to solve this.

### PR DESCRIPTION
**Pull request by raymondjacobson**
Closes #35

### CODE REVIEW

File: whereuat-ios/Views/ContactView/ContactViewCell.swift [hunk 1]
```diff
@@ -23,16 +23,15 @@ class ContactViewCell: UICollectionViewCell {
      * addContactView loads the contact data into the contact view and constrains it
      */
     func addContactView() {
-        self.contactView = ContactView(contactData: contactData)
-        self.contactView.delegate = delegate
+            self.contactView.delegate = self.delegate
```
Comment (kangp3) [inline whereuat-ios/Views/ContactView/ContactViewCell.swift]: Unindent this stuff once

File: whereuat-ios/Views/ContactView/ContactViewCell.swift [hunk 2]
```diff
@@ -23,16 +23,15 @@ class ContactViewCell: UICollectionViewCell {
...
-        self.addConstraints([leftSideConstraint, bottomConstraint, widthConstraint, heightConstraint])
+            self.contentView.addSubview(self.contactView)
+            self.contactView.translatesAutoresizingMaskIntoConstraints = false
+            let leftSideConstraint = NSLayoutConstraint(item: self.contactView, attribute: .Left, relatedBy: .Equal, toItem: self, attribute: .Left, multiplier: 1.0, constant: 0.0)
+            let bottomConstraint = NSLayoutConstraint(item: self.contactView, attribute: .Bottom, relatedBy: .Equal, toItem: self, attribute: .Bottom, multiplier: 1.0, constant: 0.0)
+            let widthConstraint = NSLayoutConstraint(item: self.contactView, attribute: .Width, relatedBy: .Equal, toItem: self, attribute: .Width, multiplier: 1.0, constant: 0.0)
+            let heightConstraint = NSLayoutConstraint(item: self.contactView, attribute: .Height, relatedBy: .Equal, toItem: self, attribute: .Height, multiplier: 1.0, constant: 0.0)
+            self.addConstraints([leftSideConstraint, bottomConstraint, widthConstraint, heightConstraint])
```
Comment (kangp3) [inline whereuat-ios/Views/ContactView/ContactViewCell.swift]: Un-indent this stuff once

**Comment by kangp3** [comment]
lgtm after comments
